{{- if and .Values.config.redis.password (not .Values.config.redis.external) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weather-proxy.fullname" . }}-redis-secret
  labels:
    {{- include "weather-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.config.redis.password | b64enc | quote }}
{{- end }}
